<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Product>Пробуждение</Product>
    <Version>0.3.0-alpha</Version>
    <Authors>Probuzhdenie contributors</Authors>
    <Description>Атмосферная low-poly игра о пробуждении героя в повторяющемся городе.</Description>
    <Copyright>Copyright © 2026 Probuzhdenie contributors</Copyright>
    <AssemblyName>Probuzhdenie</AssemblyName>
    <RootNamespace>Probuzhdenie</RootNamespace>
    <AssemblyTitle>Пробуждение</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="unreal/**/*.cs" />
    <PackageReference Include="OpenTK" Version="4.8.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.16" />
    <None Update="assets/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
