<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>../../obj/graphics-smoke/</BaseIntermediateOutputPath>
    <BaseOutputPath>../../bin/graphics-smoke/</BaseOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="VisualProbe.cs.txt" />
    <ProjectReference Include="../../Probuzhdenie.csproj" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
